Repository careem/superset, pull requests merged in 2022-09, with the labels that each got.

#51 feat(BDP-4652): Flash Sql Query Updation
  Dockerfile
  docker/run-server.sh
  secrets.sh
  superset-frontend/package.json
  superset-frontend/src/views/CRUD/flashManagement/components/FlashExtendTTl/FlashExtendTTl.tsx
  superset-frontend/src/views/CRUD/flashManagement/components/FlashGrid/FlashList.tsx
  superset-frontend/src/views/CRUD/flashManagement/components/FlashOwnership/FlashOwnership.tsx
  superset-frontend/src/views/CRUD/flashManagement/components/FlashQuery/FlashQuery.tsx
  superset-frontend/src/views/CRUD/flashManagement/components/FlashSchedule/FlashSchedule.tsx
  superset-frontend/src/views/CRUD/flashManagement/constants.ts
  superset-frontend/src/views/CRUD/flashManagement/enums.ts
  superset-frontend/src/views/CRUD/flashManagement/services/flash.service.ts
  superset-frontend/src/views/CRUD/flashManagement/types.ts
  superset/config.py
  superset/initialization/__init__.py
Labels: dev

#53 feat(flash-changes) : Flash Changes Implementation
  superset-frontend/src/views/CRUD/flashManagement/services/flash.service.ts
  superset-frontend/src/views/CRUD/flashManagement/types.ts
  superset/config.py
Labels: refactoring

#54 feat(BDP-4518): Flash Management Module
  Dockerfile
  docker-compose.yml
  docker/run-server.sh
  secrets.sh
  superset-frontend/package-lock.json
  superset-frontend/package.json
  superset-frontend/packages/superset-ui-core/package.json
  superset-frontend/packages/superset-ui-core/src/connection/FlashClient.ts
  superset-frontend/packages/superset-ui-core/src/connection/index.ts
  superset-frontend/packages/superset-ui-core/src/utils/featureFlags.ts
  superset-frontend/src/SqlLab/actions/sqlLab.js
  superset-frontend/src/SqlLab/components/SqlEditor/index.jsx
  superset-frontend/src/assets/images/icons/switch_user.svg
  superset-frontend/src/components/DatePicker/DatePicker.stories.tsx
  superset-frontend/src/components/Icons/Icon.tsx
  superset-frontend/src/components/Icons/index.tsx
  superset-frontend/src/components/ListView/ActionsBar.tsx
  superset-frontend/src/components/ListView/Filters/Date.tsx
  superset-frontend/src/components/ListView/Filters/index.tsx
  superset-frontend/src/components/ListView/types.ts
  superset-frontend/src/components/ModalTrigger/index.tsx
  superset-frontend/src/explore/components/ExploreChartHeader/index.jsx
  superset-frontend/src/explore/components/ExploreViewContainer/index.jsx
  superset-frontend/src/utils/commonHelper.ts
  superset-frontend/src/views/App.tsx
  superset-frontend/src/views/CRUD/flashManagement/components/FlashCreationButton/FlashCreationButton.tsx
  superset-frontend/src/views/CRUD/flashManagement/components/FlashExtendTTl/FlashExtendTTl.tsx
  superset-frontend/src/views/CRUD/flashManagement/components/FlashGrid/FlashList.tsx
  superset-frontend/src/views/CRUD/flashManagement/components/FlashOwnership/FlashOwnership.tsx
  superset-frontend/src/views/CRUD/flashManagement/components/FlashQuery/FlashQuery.tsx
  superset-frontend/src/views/CRUD/flashManagement/components/FlashSchedule/FlashSchedule.tsx
  superset-frontend/src/views/CRUD/flashManagement/constants.ts
  superset-frontend/src/views/CRUD/flashManagement/enums.ts
  superset-frontend/src/views/CRUD/flashManagement/services/flash.service.ts
  superset-frontend/src/views/CRUD/flashManagement/types.ts
  superset-frontend/src/views/CRUD/hooks.ts
  superset-frontend/src/views/menu.tsx
  superset-frontend/src/views/routes.tsx
  superset/config.py
  superset/connectors/sqla/models.py
  superset/databases/api.py
  superset/databases/schemas.py
  superset/datasets/api.py
  superset/db_engine_specs/base.py
  superset/db_engine_specs/presto.py
  superset/initialization/__init__.py
  superset/models/core.py
  superset/queries/saved_queries/api.py
  superset/queries/saved_queries/filters.py
  superset/views/base.py
  superset/views/core.py
  superset/views/explore_response.py
  superset/views/flash/__init__.py
  superset/views/flash/views.py
  superset/views/multi_dataset.py
Labels: release

#76 fix: Date 24 hour format issue
  superset-frontend/src/SqlLab/components/SqlEditor/index.jsx
  superset-frontend/src/views/CRUD/flash/components/FlashCreationButton/FlashCreationButton.tsx
  superset-frontend/src/views/CRUD/flash/components/FlashSchedule/FlashSchedule.tsx
Labels: bug

#75 feat(BDP-4801): View Flash Object Information
  superset-frontend/src/utils/commonHelper.ts
  superset-frontend/src/views/CRUD/flash/components/FlashExtendTTl/FlashExtendTTl.tsx
  superset-frontend/src/views/CRUD/flash/components/FlashGrid/FlashList.tsx
  superset-frontend/src/views/CRUD/flash/components/FlashQuery/FlashQuery.tsx
  superset-frontend/src/views/CRUD/flash/components/FlashView/FlashView.tsx
  superset-frontend/src/views/CRUD/flash/types.ts
Labels: enhancement
